_wandb:
    value:
        cli_version: 0.22.2
        e:
            granjcgl7rnzv2wruqddfl1b0j7uj74e:
                codePath: mainSR_dino.py
                codePathLocal: mainSR_dino.py
                cpu_count: 24
                cpu_count_logical: 24
                cudaVersion: "12.9"
                disk:
                    /:
                        total: "1065418129408"
                        used: "1037805760512"
                email: 2534172@tongji.edu.cn
                executable: /home/yifanyang/miniconda3/envs/unifmir/bin/python
                git:
                    commit: ff371b2367defddc2795ab6fb2321b203999ff0a
                    remote: https://github.com/rubiasnow12/UNiFMIR.git
                gpu: NVIDIA A100 80GB PCIe
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A100 80GB PCIe
                      uuid: GPU-fa33cb68-c7b8-95ba-f1e5-56351ec3de8a
                host: GCRAZGDL1535
                memory:
                    total: "232209711104"
                os: Linux-6.8.0-1036-azure-x86_64-with-glibc2.35
                program: /home/yifanyang/hwq/UniFMIRproject/UNiFMIR/mainSR_dino.py
                python: CPython 3.9.23
                root: /home/yifanyang/hwq/UniFMIRproject/UNiFMIR
                startedAt: "2025-10-28T05:23:44.864216Z"
                writerId: granjcgl7rnzv2wruqddfl1b0j7uj74e
        m: []
        python_version: 3.9.23
        t:
            "1":
                - 1
                - 2
                - 3
                - 41
                - 49
                - 63
                - 105
            "2":
                - 1
                - 2
                - 3
                - 41
                - 49
                - 63
                - 105
            "3":
                - 1
                - 2
                - 13
                - 16
            "4": 3.9.23
            "5": 0.22.2
            "12": 0.22.2
            "13": linux-x86_64
act:
    value: relu
batch_size:
    value: 4
betas:
    value:
        - 0.9
        - 0.999
chop:
    value: true
chunk_size:
    value: 144
cpu:
    value: false
data_test:
    value: F-actin
datamax:
    value: 100
datamin:
    value: 0
debug:
    value: false
decay:
    value: "200"
dilation:
    value: false
dir_data:
    value: null
dir_demo:
    value: null
epochs:
    value: 1000
epsilon:
    value: 1e-08
extend:
    value: .
gamma:
    value: 0.5
gan_k:
    value: 1
gclip:
    value: 0
inch:
    value: 1
inputchannel:
    value: 1
load:
    value: ""
local_rank:
    value: 0
loss:
    value: 1*L1+1*L2
lr:
    value: 5e-05
model:
    value: DINOIRv3
modelpath:
    value: experiment/DINOIRv3F-actin/model/model_best.pt
momentum:
    value: 0.9
n_GPUs:
    value: 1
n_colors:
    value: 1
n_feats:
    value: 32
n_hashes:
    value: 4
n_resblocks:
    value: 8
n_threads:
    value: 0
no_augment:
    value: false
optimizer:
    value: ADAM
patch_size:
    value: 128
precision:
    value: single
print_every:
    value: 1000
res_scale:
    value: 0.1
reset:
    value: false
resume:
    value: 0
rgb_range:
    value: 1
save:
    value: DINOIRv3F-actin/
save_gt:
    value: false
save_models:
    value: true
save_results:
    value: true
scale:
    value:
        - 2
seed:
    value: 1
self_ensemble:
    value: false
shift_mean:
    value: true
skip_threshold:
    value: 1e+08
split_batch:
    value: 1
task:
    value: -1
test_every:
    value: 2000
test_only:
    value: true
weight_decay:
    value: 0
